# Generated by Django 5.2.1 on 2025-05-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_remove_customer_user_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.AddField(
            model_name='customer',
            name='Customer_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Mã khách hàng'),
        ),
    ]
