# Generated by Django 5.2.1 on 2025-05-21 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField()),
                ('is_used', models.BooleanField(default=False)),
                ('is_booked', models.BooleanField(default=False)),
                ('capacity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TableBooked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_guests', models.PositiveIntegerField(verbose_name='Số lượng khách')),
                ('booking_time', models.DateTimeField(verbose_name='Thời gian đặt')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('status', models.CharField(choices=[('pending', 'Đang chờ xử lý'), ('confirmed', 'Đã xác nhận'), ('cancelled', 'Đã hủy'), ('completed', 'Đã hoàn thành')], default='pending', max_length=10, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='Khách hàng')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.table', verbose_name='Bàn')),
            ],
        ),
    ]
