# Generated by Django 5.2.1 on 2025-05-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Danh mục món ăn',
                'verbose_name_plural': 'Các danh mục món ăn',
            },
        ),
        migrations.CreateModel(
            name='FoodOrdered',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('dine-in', 'Tại nhà hàng'), ('takeaway', 'Mang về')], default='dine-in', max_length=10, verbose_name='Loại đơn hàng')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tổng tiền (VNĐ)')),
                ('status', models.CharField(choices=[('pending', 'Đang chờ xử lý'), ('preparing', 'Đang chuẩn bị'), ('ready', 'Sẵn sàng giao'), ('completed', 'Đã hoàn thành'), ('cancelled', 'Đã hủy')], default='pending', max_length=10, verbose_name='Trạng thái')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú đơn hàng')),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Các đơn hàng',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Tên món ăn')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá (VNĐ)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_images/', verbose_name='Hình ảnh')),
                ('is_available', models.BooleanField(default=True, verbose_name='Còn hàng')),
            ],
            options={
                'verbose_name': 'Món ăn',
                'verbose_name_plural': 'Thực đơn',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Số lượng')),
                ('price_at_order', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá tại thời điểm đặt (VNĐ)')),
            ],
            options={
                'verbose_name': 'Chi tiết đơn hàng',
                'verbose_name_plural': 'Các chi tiết đơn hàng',
            },
        ),
    ]
