# Generated by Django 5.2.1 on 2025-05-21 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('menu', '0001_initial'),
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodordered',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='Khách hàng'),
        ),
        migrations.AddField(
            model_name='foodordered',
            name='table',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.table', verbose_name='Đặt bàn liên quan'),
        ),
        migrations.AddField(
            model_name='menu',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='menu.category', verbose_name='Danh mục'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.menu', verbose_name='Món ăn'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.foodordered', verbose_name='Đơn hàng'),
        ),
    ]
