# Generated by Django 5.2.1 on 2025-05-22 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_initial'),
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodordered',
            name='customer',
        ),
        migrations.AlterField(
            model_name='foodordered',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.table', verbose_name='Đặt bàn liên quan'),
        ),
    ]
